version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - devops-agent_default

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - devops-agent_default

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - devops-agent_default

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - /home/ubuntu/devops-agent/logs:/logs
      - ./promtail-config.yml:/etc/promtail/config.yml
    networks:
      - devops-agent_default

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - devops-agent_default

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    networks:
      - devops-agent_default

  dashboard:
    build: ../dashboard
    container_name: dashboard
    ports:
      - "5000:5000"
    volumes:
      - ../dashboard:/app
      - ../logs:/logs
    networks:
      - devops-agent_default

networks:
  devops-agent_default:
    driver: bridge
